# Generated by Django 5.2.15 on 2026-07-01 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(help_text='Name of the doctor or clinic (e.g., Dr. Smith)', max_length=200)),
                ('location', models.CharField(help_text='Location/address of the appointment', max_length=300)),
                ('date_time', models.DateTimeField(help_text='Date and time of the scheduled appointment')),
                ('user', models.ForeignKey(help_text='User (senior) this appointment belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medication (e.g., Lisinopril)', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage details (e.g., 10mg, 1 tablet)', max_length=100)),
                ('time_to_take', models.TimeField(help_text='Time of day when the medication should be taken')),
                ('user', models.ForeignKey(help_text='User (senior) this medication belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
